### ISSUE TITLE
NullPointerExceptions when using dismax

### ISSUE THREAD

**Issue by karussell** [tjake/Solandra#50]
When using the demo:
- change dismax to this (so that all fields can be found)
  <requestHandler name="dismax" class="solr.SearchHandler" >
    <lst name="defaults">
     <str name="defType">dismax</str>
     <str name="echoParams">explicit</str>
     <float name="tie">0.01</float>
     <str name="qf">
        text^0.5 title^2
     </str>
     <str name="mm">
        2&lt;-1 5&lt;-2 6&lt;90%
     </str>
     <int name="ps">100</int>
     <str name="q.alt">_:_</str>
    </lst>
  </requestHandler>
- feed the reuters demo schema.xml (not the data)
- http://localhost:8983/solandra/reuters/select?q=&qt=dismax
  =>
  
    java.lang.NullPointerException
    at lucandra.LucandraAllTermDocs.fillDocBuffer(LucandraAllTermDocs.java:150)
   at lucandra.LucandraAllTermDocs.<init>(LucandraAllTermDocs.java:63)
   at lucandra.IndexReader.termDocs(IndexReader.java:404)
   at org.apache.solr.search.SolrIndexReader.termDocs(SolrIndexReader.java:320)
   at org.apache.lucene.search.MatchAllDocsQuery$MatchAllScorer.<init>(MatchAllDocsQuery.java:55)
   at org.apache.lucene.search.MatchAllDocsQuery$MatchAllDocsWeight.scorer(MatchAllDocsQuery.java:128)
   at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:250)
   at org.apache.lucene.search.Searcher.search(Searcher.java:171)
   at org.apache.solr.search.SolrIndexSearcher.getDocListNC(SolrIndexSearcher.java:988)
   at org.apache.solr.search.SolrIndexSearcher.getDocListC(SolrIndexSearcher.java:884)
   at org.apache.solr.search.SolrIndexSearcher.search(SolrIndexSearcher.java:341)
   at org.apache.solr.handler.component.QueryComponent.process(QueryComponent.java:182)
   at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:195)
   at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:131)
   at org.apache.solr.core.SolrCore.execute(SolrCore.java:1316)
   at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:338)
   at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:169)
   at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:241)
   at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:133)

Now sometimes the exception does _not_ occur after data feeding. But the
initial query always failed in my tests.

When I'm querying while feeding sometimes other exception (randomly?)
occured
E.g.
http://localhost:8983/solandra/reuters/select?q=text&qt=dismax
=>

```
    java.lang.NullPointerException
at lucandra.LucandraTermEnum.skipTo(LucandraTermEnum.java:87)
at lucandra.LucandraTermDocs.seek(LucandraTermDocs.java:115)
at org.apache.lucene.index.IndexReader.termDocs(IndexReader.java:1103)
at lucandra.IndexReader.termDocs(IndexReader.java:406)
at org.apache.solr.search.SolrIndexReader.termDocs(SolrIndexReader.java:320)
at org.apache.lucene.search.TermQuery$TermWeight.scorer(TermQuery.java:67)
at org.apache.lucene.search.DisjunctionMaxQuery$DisjunctionMaxWeight.scorer(DisjunctionMaxQuery.java:144)
at org.apache.lucene.search.BooleanQuery$BooleanWeight.scorer(BooleanQuery.java:297)
at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:250)
at org.apache.lucene.search.Searcher.search(Searcher.java:171)
at org.apache.solr.search.SolrIndexSearcher.getDocListNC(SolrIndexSearcher.java:988)
at org.apache.solr.search.SolrIndexSearcher.getDocListC(SolrIndexSearcher.java:884)
at org.apache.solr.search.SolrIndexSearcher.search(SolrIndexSearcher.java:341)
at org.apache.solr.handler.component.QueryComponent.process(QueryComponent.java:182)
at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:195)
at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:131)
at org.apache.solr.core.SolrCore.execute(SolrCore.java:1316)
at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:338)
at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:169)
at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:241)
at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:133)
```

and after refresh this one happened:

java.lang.NullPointerException
    at lucandra.LucandraTermEnum.docFreq(LucandraTermEnum.java:99)
    at lucandra.IndexReader.docFreq(IndexReader.java:177)
    at org.apache.solr.search.SolrIndexReader.docFreq(SolrIndexReader.java:308)
    at org.apache.lucene.search.IndexSearcher.docFreq(IndexSearcher.java:147)
    at org.apache.lucene.search.Similarity.idfExplain(Similarity.java:765)
    at org.apache.lucene.search.TermQuery$TermWeight.<init>(TermQuery.java:46)
    at org.apache.lucene.search.TermQuery.createWeight(TermQuery.java:146)
    at org.apache.lucene.search.DisjunctionMaxQuery$DisjunctionMaxWeight.<init>(DisjunctionMaxQuery.java:106)
    at org.apache.lucene.search.DisjunctionMaxQuery.createWeight(DisjunctionMaxQuery.java:177)
    at org.apache.lucene.search.BooleanQuery$BooleanWeight.<init>(BooleanQuery.java:184)
    at org.apache.lucene.search.BooleanQuery.createWeight(BooleanQuery.java:415)
    at org.apache.lucene.search.Query.weight(Query.java:99)
    at org.apache.lucene.search.Searcher.createWeight(Searcher.java:230)
    at org.apache.lucene.search.Searcher.search(Searcher.java:171)
    at org.apache.solr.search.SolrIndexSearcher.getDocListNC(SolrIndexSearcher.java:988)
    at org.apache.solr.search.SolrIndexSearcher.getDocListC(SolrIndexSearcher.java:884)
    at org.apache.solr.search.SolrIndexSearcher.search(SolrIndexSearcher.java:341)
    at org.apache.solr.handler.component.QueryComponent.process(QueryComponent.java:182)
    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:195)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:131)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:1316)
    at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:338)
    at solandra.SolandraDispatchFilter.execute(SolandraDispatchFilter.java:169)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:241)
    at solandra.SolandraDispatchFilter.doFilter(SolandraDispatchFilter.java:133)

**Comment by tjake** [comment]
Thanks, I'll be pushing a bunch of internal changes soon and will address this

**Comment by tjake** [comment]
I've pushed the changes I mentioned, please take a look.

No longer getting exceptions but the dismax queries seem to only return results after a similar query on standard search handler. I must be doing something wrong.

**Comment by karussell** [comment]
Could it be that simply the following is missing from the dismax handler section?

```
 <arr name="components">
  <str>query</str>
  <str>solandraComponent</str>
  <str>facet</str>
  <str>mlt</str>
  <str>highlight</str>
  <str>stats</str>
  <str>debug</str>
 </arr>
```

Without that I didn't got results. With that all seems to be ok.

I'll report in tomorrow (or in the next days ;)) if my usecase for dismax still fails with that addition.

**Comment by karussell** [comment]
Ok, nice. Feeding and querying from jetwick works now (with the above change) :-)

So, thanks for the changes!

**Comment by tjake** [comment]
Cool is it live? what's the url?

**Comment by karussell** [comment]
sadly not yet, due too some other problems (see new issues). Also sorting seems to be slow. Or is only sort by latest date supported?

**Comment by tjake** [comment]
How many many documents in the indexes?

Are you running this on a single node?  Solandra won't be faster than Solr on a single node keep in mind.  Also you have shards.at.once=2 which doesn't make sense if you have 1 node.  It should roughly be the same as the number of nodes in your cluster.

**Comment by karussell** [comment]
> How many many documents in the indexes?

there were only 5K I think

> Are you running this on a single node?

for this test, yes.

> Solandra won't be faster than Solr on a single node keep in mind.

Also for large indices >10GB?

> Also you have shards.at.once=2 which doesn't make sense if you have 1 node. 

ok

**Comment by karussell** [comment]
> Also you have shards.at.once=2 which doesn't make sense if you have 1 node.

also if the node has more than one core?

**Comment by tjake** [comment]
it will help with write tps but it will increase the amount of memory needed :)

**Comment by karussell** [comment]
ah, now I understand. so "at.once" is important here ... sorry

**Comment by tjake** [comment]
How many documents in your index?

**Comment by karussell** [comment]
ok, but this issue here is fixed. I'll close, ok?

**Comment by karussell** [comment]
> How many documents in your index?

there were only 5K I think
